"""Public, implementation-independent engine contracts."""

from farcel.contracts.errors import EngineError, ErrorCode
from farcel.contracts.models import (
    CapabilitySet,
    DefaultExperiment,
    ExportReport,
    InputUpdate,
    InterfaceCapability,
    InterfaceType,
    ModelMetadata,
    ResultChunk,
    RunSummary,
    SessionHandle,
    SimulationConfig,
    SimulationResult,
    SimulationState,
    StepResult,
    StepStatus,
    ValidationIssue,
    ValidationReport,
    VariableMetadata,
)
from farcel.contracts.ports import (
    ModelImporter,
    ResultExporter,
    SessionFactory,
    SimulationEngine,
    SimulationSession,
)

__all__ = [
    "CapabilitySet",
    "DefaultExperiment",
    "EngineError",
    "ErrorCode",
    "ExportReport",
    "InputUpdate",
    "InterfaceType",
    "InterfaceCapability",
    "ModelImporter",
    "ModelMetadata",
    "ResultChunk",
    "ResultExporter",
    "RunSummary",
    "SessionFactory",
    "SessionHandle",
    "SimulationConfig",
    "SimulationEngine",
    "SimulationResult",
    "SimulationSession",
    "SimulationState",
    "StepResult",
    "StepStatus",
    "ValidationIssue",
    "ValidationReport",
    "VariableMetadata",
]
